language: python
python: 2.7
services: redis-server
addons:
  postgresql: "9.4"
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - ACTION=loadtest_tutorial
    - ACTION=loadtest_simulation
before_script:
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres
install:
    - if [[ $ACTION != loadtest_tutorial && $ACTION != loadtest_simulation ]]; then pip install tox; fi
script:
    - if [[ $ACTION != loadtest_tutorial && $ACTION != loadtest_simulation ]]; then tox -e $TOX_ENV; fi
    - if [[ $ACTION == loadtest_simulation ]]; then make loadtest-check-simulation; fi
    - if [[ $ACTION == loadtest_tutorial ]]; then make loadtest-check-tutorial; fi
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
